// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/app/models/proto/dto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type CreateShortLinkJSONRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Request       *CreateShortLinkJSONRequest_Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONRequest) Reset() {
	*x = CreateShortLinkJSONRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONRequest) ProtoMessage() {}

func (x *CreateShortLinkJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortLinkJSONRequest) GetRequest() *CreateShortLinkJSONRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type CreateShortLinkJSONResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Response      *CreateShortLinkJSONResponse_Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONResponse) Reset() {
	*x = CreateShortLinkJSONResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONResponse) ProtoMessage() {}

func (x *CreateShortLinkJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortLinkJSONResponse) GetResponse() *CreateShortLinkJSONResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type CreateShortLinkJSONBatchRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Requests      []*CreateShortLinkJSONBatchRequest_Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONBatchRequest) Reset() {
	*x = CreateShortLinkJSONBatchRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONBatchRequest) ProtoMessage() {}

func (x *CreateShortLinkJSONBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShortLinkJSONBatchRequest) GetRequests() []*CreateShortLinkJSONBatchRequest_Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type CreateShortLinkJSONBatchResponse struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Responses     []*CreateShortLinkJSONBatchResponse_Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONBatchResponse) Reset() {
	*x = CreateShortLinkJSONBatchResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONBatchResponse) ProtoMessage() {}

func (x *CreateShortLinkJSONBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShortLinkJSONBatchResponse) GetResponses() []*CreateShortLinkJSONBatchResponse_Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkRequest) Reset() {
	*x = GetShortLinkRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkRequest) ProtoMessage() {}

func (x *GetShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{6}
}

func (x *GetShortLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkResponse) Reset() {
	*x = GetShortLinkResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkResponse) ProtoMessage() {}

func (x *GetShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkResponse.ProtoReflect.Descriptor instead.
func (*GetShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{7}
}

func (x *GetShortLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetShortLinksOfUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinksOfUserRequest) Reset() {
	*x = GetShortLinksOfUserRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinksOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinksOfUserRequest) ProtoMessage() {}

func (x *GetShortLinksOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinksOfUserRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinksOfUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{8}
}

type GetShortLinksOfUserResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Responses     []*GetShortLinksOfUserResponse_Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinksOfUserResponse) Reset() {
	*x = GetShortLinksOfUserResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinksOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinksOfUserResponse) ProtoMessage() {}

func (x *GetShortLinksOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinksOfUserResponse.ProtoReflect.Descriptor instead.
func (*GetShortLinksOfUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{9}
}

func (x *GetShortLinksOfUserResponse) GetResponses() []*GetShortLinksOfUserResponse_Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type DeleteURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsRequest) Reset() {
	*x = DeleteURLsRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsRequest) ProtoMessage() {}

func (x *DeleteURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteURLsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsResponse) Reset() {
	*x = DeleteURLsResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsResponse) ProtoMessage() {}

func (x *DeleteURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteURLsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{12}
}

type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{13}
}

func (x *PingDBResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{14}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          uint64                 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         uint64                 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{15}
}

func (x *StatsResponse) GetUrls() uint64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() uint64 {
	if x != nil {
		return x.Users
	}
	return 0
}

type CreateShortLinkJSONRequest_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONRequest_Request) Reset() {
	*x = CreateShortLinkJSONRequest_Request{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONRequest_Request) ProtoMessage() {}

func (x *CreateShortLinkJSONRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONRequest_Request.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONRequest_Request) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateShortLinkJSONRequest_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortLinkJSONResponse_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONResponse_Response) Reset() {
	*x = CreateShortLinkJSONResponse_Response{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONResponse_Response) ProtoMessage() {}

func (x *CreateShortLinkJSONResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONResponse_Response.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONResponse_Response) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateShortLinkJSONResponse_Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateShortLinkJSONBatchRequest_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONBatchRequest_Request) Reset() {
	*x = CreateShortLinkJSONBatchRequest_Request{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONBatchRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONBatchRequest_Request) ProtoMessage() {}

func (x *CreateShortLinkJSONBatchRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONBatchRequest_Request.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONBatchRequest_Request) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateShortLinkJSONBatchRequest_Request) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateShortLinkJSONBatchRequest_Request) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateShortLinkJSONBatchResponse_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkJSONBatchResponse_Response) Reset() {
	*x = CreateShortLinkJSONBatchResponse_Response{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkJSONBatchResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkJSONBatchResponse_Response) ProtoMessage() {}

func (x *CreateShortLinkJSONBatchResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkJSONBatchResponse_Response.ProtoReflect.Descriptor instead.
func (*CreateShortLinkJSONBatchResponse_Response) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateShortLinkJSONBatchResponse_Response) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateShortLinkJSONBatchResponse_Response) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetShortLinksOfUserResponse_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinksOfUserResponse_Response) Reset() {
	*x = GetShortLinksOfUserResponse_Response{}
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinksOfUserResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinksOfUserResponse_Response) ProtoMessage() {}

func (x *GetShortLinksOfUserResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_models_proto_dto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinksOfUserResponse_Response.ProtoReflect.Descriptor instead.
func (*GetShortLinksOfUserResponse_Response) Descriptor() ([]byte, []int) {
	return file_internal_app_models_proto_dto_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetShortLinksOfUserResponse_Response) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetShortLinksOfUserResponse_Response) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_internal_app_models_proto_dto_proto protoreflect.FileDescriptor

const file_internal_app_models_proto_dto_proto_rawDesc = "" +
	"\n" +
	"#internal/app/models/proto/dto.proto\x12\x05proto\";\n" +
	"\x16CreateShortLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"6\n" +
	"\x17CreateShortLinkResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"~\n" +
	"\x1aCreateShortLinkJSONRequest\x12C\n" +
	"\arequest\x18\x01 \x01(\v2).proto.CreateShortLinkJSONRequest.RequestR\arequest\x1a\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8a\x01\n" +
	"\x1bCreateShortLinkJSONResponse\x12G\n" +
	"\bresponse\x18\x01 \x01(\v2+.proto.CreateShortLinkJSONResponse.ResponseR\bresponse\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\xc2\x01\n" +
	"\x1fCreateShortLinkJSONBatchRequest\x12J\n" +
	"\brequests\x18\x01 \x03(\v2..proto.CreateShortLinkJSONBatchRequest.RequestR\brequests\x1aS\n" +
	"\aRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\xc2\x01\n" +
	" CreateShortLinkJSONBatchResponse\x12N\n" +
	"\tresponses\x18\x01 \x03(\v20.proto.CreateShortLinkJSONBatchResponse.ResponseR\tresponses\x1aN\n" +
	"\bResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"%\n" +
	"\x13GetShortLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x14GetShortLinkResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"\x1c\n" +
	"\x1aGetShortLinksOfUserRequest\"\xb4\x01\n" +
	"\x1bGetShortLinksOfUserResponse\x12I\n" +
	"\tresponses\x18\x01 \x03(\v2+.proto.GetShortLinksOfUserResponse.ResponseR\tresponses\x1aJ\n" +
	"\bResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"'\n" +
	"\x11DeleteURLsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\",\n" +
	"\x12DeleteURLsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0f\n" +
	"\rPingDBRequest\"(\n" +
	"\x0ePingDBResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0e\n" +
	"\fStatsRequest\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x04R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x04R\x05users2\x90\x05\n" +
	"\fURLShortener\x12R\n" +
	"\x0fCreateShortLink\x12\x1d.proto.CreateShortLinkRequest\x1a\x1e.proto.CreateShortLinkResponse\"\x00\x12^\n" +
	"\x13CreateShortLinkJSON\x12!.proto.CreateShortLinkJSONRequest\x1a\".proto.CreateShortLinkJSONResponse\"\x00\x12m\n" +
	"\x18CreateShortLinkJSONBatch\x12&.proto.CreateShortLinkJSONBatchRequest\x1a'.proto.CreateShortLinkJSONBatchResponse\"\x00\x12I\n" +
	"\fGetShortLink\x12\x1a.proto.GetShortLinkRequest\x1a\x1b.proto.GetShortLinkResponse\"\x00\x12^\n" +
	"\x13GetShortLinksOfUser\x12!.proto.GetShortLinksOfUserRequest\x1a\".proto.GetShortLinksOfUserResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteURLs\x12\x18.proto.DeleteURLsRequest\x1a\x19.proto.DeleteURLsResponse\"\x00\x127\n" +
	"\x06PingDB\x12\x14.proto.PingDBRequest\x1a\x15.proto.PingDBResponse\"\x00\x124\n" +
	"\x05Stats\x12\x13.proto.StatsRequest\x1a\x14.proto.StatsResponse\"\x00B>Z<github.com/RexArseny/url_shortener/internal/app/models/protob\x06proto3"

var (
	file_internal_app_models_proto_dto_proto_rawDescOnce sync.Once
	file_internal_app_models_proto_dto_proto_rawDescData []byte
)

func file_internal_app_models_proto_dto_proto_rawDescGZIP() []byte {
	file_internal_app_models_proto_dto_proto_rawDescOnce.Do(func() {
		file_internal_app_models_proto_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_models_proto_dto_proto_rawDesc), len(file_internal_app_models_proto_dto_proto_rawDesc)))
	})
	return file_internal_app_models_proto_dto_proto_rawDescData
}

var file_internal_app_models_proto_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_app_models_proto_dto_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil),                    // 0: proto.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil),                   // 1: proto.CreateShortLinkResponse
	(*CreateShortLinkJSONRequest)(nil),                // 2: proto.CreateShortLinkJSONRequest
	(*CreateShortLinkJSONResponse)(nil),               // 3: proto.CreateShortLinkJSONResponse
	(*CreateShortLinkJSONBatchRequest)(nil),           // 4: proto.CreateShortLinkJSONBatchRequest
	(*CreateShortLinkJSONBatchResponse)(nil),          // 5: proto.CreateShortLinkJSONBatchResponse
	(*GetShortLinkRequest)(nil),                       // 6: proto.GetShortLinkRequest
	(*GetShortLinkResponse)(nil),                      // 7: proto.GetShortLinkResponse
	(*GetShortLinksOfUserRequest)(nil),                // 8: proto.GetShortLinksOfUserRequest
	(*GetShortLinksOfUserResponse)(nil),               // 9: proto.GetShortLinksOfUserResponse
	(*DeleteURLsRequest)(nil),                         // 10: proto.DeleteURLsRequest
	(*DeleteURLsResponse)(nil),                        // 11: proto.DeleteURLsResponse
	(*PingDBRequest)(nil),                             // 12: proto.PingDBRequest
	(*PingDBResponse)(nil),                            // 13: proto.PingDBResponse
	(*StatsRequest)(nil),                              // 14: proto.StatsRequest
	(*StatsResponse)(nil),                             // 15: proto.StatsResponse
	(*CreateShortLinkJSONRequest_Request)(nil),        // 16: proto.CreateShortLinkJSONRequest.Request
	(*CreateShortLinkJSONResponse_Response)(nil),      // 17: proto.CreateShortLinkJSONResponse.Response
	(*CreateShortLinkJSONBatchRequest_Request)(nil),   // 18: proto.CreateShortLinkJSONBatchRequest.Request
	(*CreateShortLinkJSONBatchResponse_Response)(nil), // 19: proto.CreateShortLinkJSONBatchResponse.Response
	(*GetShortLinksOfUserResponse_Response)(nil),      // 20: proto.GetShortLinksOfUserResponse.Response
}
var file_internal_app_models_proto_dto_proto_depIdxs = []int32{
	16, // 0: proto.CreateShortLinkJSONRequest.request:type_name -> proto.CreateShortLinkJSONRequest.Request
	17, // 1: proto.CreateShortLinkJSONResponse.response:type_name -> proto.CreateShortLinkJSONResponse.Response
	18, // 2: proto.CreateShortLinkJSONBatchRequest.requests:type_name -> proto.CreateShortLinkJSONBatchRequest.Request
	19, // 3: proto.CreateShortLinkJSONBatchResponse.responses:type_name -> proto.CreateShortLinkJSONBatchResponse.Response
	20, // 4: proto.GetShortLinksOfUserResponse.responses:type_name -> proto.GetShortLinksOfUserResponse.Response
	0,  // 5: proto.URLShortener.CreateShortLink:input_type -> proto.CreateShortLinkRequest
	2,  // 6: proto.URLShortener.CreateShortLinkJSON:input_type -> proto.CreateShortLinkJSONRequest
	4,  // 7: proto.URLShortener.CreateShortLinkJSONBatch:input_type -> proto.CreateShortLinkJSONBatchRequest
	6,  // 8: proto.URLShortener.GetShortLink:input_type -> proto.GetShortLinkRequest
	8,  // 9: proto.URLShortener.GetShortLinksOfUser:input_type -> proto.GetShortLinksOfUserRequest
	10, // 10: proto.URLShortener.DeleteURLs:input_type -> proto.DeleteURLsRequest
	12, // 11: proto.URLShortener.PingDB:input_type -> proto.PingDBRequest
	14, // 12: proto.URLShortener.Stats:input_type -> proto.StatsRequest
	1,  // 13: proto.URLShortener.CreateShortLink:output_type -> proto.CreateShortLinkResponse
	3,  // 14: proto.URLShortener.CreateShortLinkJSON:output_type -> proto.CreateShortLinkJSONResponse
	5,  // 15: proto.URLShortener.CreateShortLinkJSONBatch:output_type -> proto.CreateShortLinkJSONBatchResponse
	7,  // 16: proto.URLShortener.GetShortLink:output_type -> proto.GetShortLinkResponse
	9,  // 17: proto.URLShortener.GetShortLinksOfUser:output_type -> proto.GetShortLinksOfUserResponse
	11, // 18: proto.URLShortener.DeleteURLs:output_type -> proto.DeleteURLsResponse
	13, // 19: proto.URLShortener.PingDB:output_type -> proto.PingDBResponse
	15, // 20: proto.URLShortener.Stats:output_type -> proto.StatsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_app_models_proto_dto_proto_init() }
func file_internal_app_models_proto_dto_proto_init() {
	if File_internal_app_models_proto_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_models_proto_dto_proto_rawDesc), len(file_internal_app_models_proto_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_models_proto_dto_proto_goTypes,
		DependencyIndexes: file_internal_app_models_proto_dto_proto_depIdxs,
		MessageInfos:      file_internal_app_models_proto_dto_proto_msgTypes,
	}.Build()
	File_internal_app_models_proto_dto_proto = out.File
	file_internal_app_models_proto_dto_proto_goTypes = nil
	file_internal_app_models_proto_dto_proto_depIdxs = nil
}
