// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: create_short_link_request.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortLinkRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OriginalUrl *OriginalURL           `protobuf:"bytes,1,opt,name=original_url,json=originalUrl"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_create_short_link_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_short_link_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateShortLinkRequest) GetOriginalUrl() *OriginalURL {
	if x != nil {
		return x.xxx_hidden_OriginalUrl
	}
	return nil
}

func (x *CreateShortLinkRequest) SetOriginalUrl(v *OriginalURL) {
	x.xxx_hidden_OriginalUrl = v
}

func (x *CreateShortLinkRequest) HasOriginalUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OriginalUrl != nil
}

func (x *CreateShortLinkRequest) ClearOriginalUrl() {
	x.xxx_hidden_OriginalUrl = nil
}

type CreateShortLinkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OriginalUrl *OriginalURL
}

func (b0 CreateShortLinkRequest_builder) Build() *CreateShortLinkRequest {
	m0 := &CreateShortLinkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OriginalUrl = b.OriginalUrl
	return m0
}

var File_create_short_link_request_proto protoreflect.FileDescriptor

const file_create_short_link_request_proto_rawDesc = "" +
	"\n" +
	"\x1fcreate_short_link_request.proto\x12\vproto.model\x1a\x12original_url.proto\x1a!google/protobuf/go_features.proto\"U\n" +
	"\x16CreateShortLinkRequest\x12;\n" +
	"\foriginal_url\x18\x01 \x01(\v2\x18.proto.model.OriginalURLR\voriginalUrlBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_create_short_link_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_create_short_link_request_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil), // 0: proto.model.CreateShortLinkRequest
	(*OriginalURL)(nil),            // 1: proto.model.OriginalURL
}
var file_create_short_link_request_proto_depIdxs = []int32{
	1, // 0: proto.model.CreateShortLinkRequest.original_url:type_name -> proto.model.OriginalURL
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_create_short_link_request_proto_init() }
func file_create_short_link_request_proto_init() {
	if File_create_short_link_request_proto != nil {
		return
	}
	file_original_url_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_create_short_link_request_proto_rawDesc), len(file_create_short_link_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_create_short_link_request_proto_goTypes,
		DependencyIndexes: file_create_short_link_request_proto_depIdxs,
		MessageInfos:      file_create_short_link_request_proto_msgTypes,
	}.Build()
	File_create_short_link_request_proto = out.File
	file_create_short_link_request_proto_goTypes = nil
	file_create_short_link_request_proto_depIdxs = nil
}
