// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: delete_urls_response.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteURLsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status *Status                `protobuf:"bytes,1,opt,name=status"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteURLsResponse) Reset() {
	*x = DeleteURLsResponse{}
	mi := &file_delete_urls_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsResponse) ProtoMessage() {}

func (x *DeleteURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delete_urls_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteURLsResponse) GetStatus() *Status {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DeleteURLsResponse) SetStatus(v *Status) {
	x.xxx_hidden_Status = v
}

func (x *DeleteURLsResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DeleteURLsResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DeleteURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *Status
}

func (b0 DeleteURLsResponse_builder) Build() *DeleteURLsResponse {
	m0 := &DeleteURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

var File_delete_urls_response_proto protoreflect.FileDescriptor

const file_delete_urls_response_proto_rawDesc = "" +
	"\n" +
	"\x1adelete_urls_response.proto\x12\vproto.model\x1a\fstatus.proto\x1a!google/protobuf/go_features.proto\"A\n" +
	"\x12DeleteURLsResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.proto.model.StatusR\x06statusBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_delete_urls_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_delete_urls_response_proto_goTypes = []any{
	(*DeleteURLsResponse)(nil), // 0: proto.model.DeleteURLsResponse
	(*Status)(nil),             // 1: proto.model.Status
}
var file_delete_urls_response_proto_depIdxs = []int32{
	1, // 0: proto.model.DeleteURLsResponse.status:type_name -> proto.model.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delete_urls_response_proto_init() }
func file_delete_urls_response_proto_init() {
	if File_delete_urls_response_proto != nil {
		return
	}
	file_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delete_urls_response_proto_rawDesc), len(file_delete_urls_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delete_urls_response_proto_goTypes,
		DependencyIndexes: file_delete_urls_response_proto_depIdxs,
		MessageInfos:      file_delete_urls_response_proto_msgTypes,
	}.Build()
	File_delete_urls_response_proto = out.File
	file_delete_urls_response_proto_goTypes = nil
	file_delete_urls_response_proto_depIdxs = nil
}
