// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: get_short_links_of_user_request.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShortLinksOfUserRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinksOfUserRequest) Reset() {
	*x = GetShortLinksOfUserRequest{}
	mi := &file_get_short_links_of_user_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinksOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinksOfUserRequest) ProtoMessage() {}

func (x *GetShortLinksOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_short_links_of_user_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetShortLinksOfUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetShortLinksOfUserRequest_builder) Build() *GetShortLinksOfUserRequest {
	m0 := &GetShortLinksOfUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_get_short_links_of_user_request_proto protoreflect.FileDescriptor

const file_get_short_links_of_user_request_proto_rawDesc = "" +
	"\n" +
	"%get_short_links_of_user_request.proto\x12\vproto.model\x1a!google/protobuf/go_features.proto\"\x1c\n" +
	"\x1aGetShortLinksOfUserRequestBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_get_short_links_of_user_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_get_short_links_of_user_request_proto_goTypes = []any{
	(*GetShortLinksOfUserRequest)(nil), // 0: proto.model.GetShortLinksOfUserRequest
}
var file_get_short_links_of_user_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_short_links_of_user_request_proto_init() }
func file_get_short_links_of_user_request_proto_init() {
	if File_get_short_links_of_user_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_short_links_of_user_request_proto_rawDesc), len(file_get_short_links_of_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_short_links_of_user_request_proto_goTypes,
		DependencyIndexes: file_get_short_links_of_user_request_proto_depIdxs,
		MessageInfos:      file_get_short_links_of_user_request_proto_msgTypes,
	}.Build()
	File_get_short_links_of_user_request_proto = out.File
	file_get_short_links_of_user_request_proto_goTypes = nil
	file_get_short_links_of_user_request_proto_depIdxs = nil
}
