// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: get_short_links_of_user_response.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShortLinksOfUserResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserUrls *[]*UserURLs           `protobuf:"bytes,1,rep,name=user_urls,json=userUrls"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetShortLinksOfUserResponse) Reset() {
	*x = GetShortLinksOfUserResponse{}
	mi := &file_get_short_links_of_user_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinksOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinksOfUserResponse) ProtoMessage() {}

func (x *GetShortLinksOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_short_links_of_user_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetShortLinksOfUserResponse) GetUserUrls() []*UserURLs {
	if x != nil {
		if x.xxx_hidden_UserUrls != nil {
			return *x.xxx_hidden_UserUrls
		}
	}
	return nil
}

func (x *GetShortLinksOfUserResponse) SetUserUrls(v []*UserURLs) {
	x.xxx_hidden_UserUrls = &v
}

type GetShortLinksOfUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserUrls []*UserURLs
}

func (b0 GetShortLinksOfUserResponse_builder) Build() *GetShortLinksOfUserResponse {
	m0 := &GetShortLinksOfUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserUrls = &b.UserUrls
	return m0
}

var File_get_short_links_of_user_response_proto protoreflect.FileDescriptor

const file_get_short_links_of_user_response_proto_rawDesc = "" +
	"\n" +
	"&get_short_links_of_user_response.proto\x12\vproto.model\x1a\x0fuser_urls.proto\x1a!google/protobuf/go_features.proto\"Q\n" +
	"\x1bGetShortLinksOfUserResponse\x122\n" +
	"\tuser_urls\x18\x01 \x03(\v2\x15.proto.model.UserURLsR\buserUrlsBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_get_short_links_of_user_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_get_short_links_of_user_response_proto_goTypes = []any{
	(*GetShortLinksOfUserResponse)(nil), // 0: proto.model.GetShortLinksOfUserResponse
	(*UserURLs)(nil),                    // 1: proto.model.UserURLs
}
var file_get_short_links_of_user_response_proto_depIdxs = []int32{
	1, // 0: proto.model.GetShortLinksOfUserResponse.user_urls:type_name -> proto.model.UserURLs
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_get_short_links_of_user_response_proto_init() }
func file_get_short_links_of_user_response_proto_init() {
	if File_get_short_links_of_user_response_proto != nil {
		return
	}
	file_user_urls_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_short_links_of_user_response_proto_rawDesc), len(file_get_short_links_of_user_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_short_links_of_user_response_proto_goTypes,
		DependencyIndexes: file_get_short_links_of_user_response_proto_depIdxs,
		MessageInfos:      file_get_short_links_of_user_response_proto_msgTypes,
	}.Build()
	File_get_short_links_of_user_response_proto = out.File
	file_get_short_links_of_user_response_proto_goTypes = nil
	file_get_short_links_of_user_response_proto_depIdxs = nil
}
