// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: original_url.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginalURL struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OriginalUrl *string                `protobuf:"bytes,1,opt,name=original_url,json=originalUrl"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OriginalURL) Reset() {
	*x = OriginalURL{}
	mi := &file_original_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalURL) ProtoMessage() {}

func (x *OriginalURL) ProtoReflect() protoreflect.Message {
	mi := &file_original_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OriginalURL) GetOriginalUrl() string {
	if x != nil {
		if x.xxx_hidden_OriginalUrl != nil {
			return *x.xxx_hidden_OriginalUrl
		}
		return ""
	}
	return ""
}

func (x *OriginalURL) SetOriginalUrl(v string) {
	x.xxx_hidden_OriginalUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *OriginalURL) HasOriginalUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OriginalURL) ClearOriginalUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OriginalUrl = nil
}

type OriginalURL_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OriginalUrl *string
}

func (b0 OriginalURL_builder) Build() *OriginalURL {
	m0 := &OriginalURL{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OriginalUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_OriginalUrl = b.OriginalUrl
	}
	return m0
}

var File_original_url_proto protoreflect.FileDescriptor

const file_original_url_proto_rawDesc = "" +
	"\n" +
	"\x12original_url.proto\x12\vproto.model\x1a!google/protobuf/go_features.proto\"0\n" +
	"\vOriginalURL\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrlBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_original_url_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_original_url_proto_goTypes = []any{
	(*OriginalURL)(nil), // 0: proto.model.OriginalURL
}
var file_original_url_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_original_url_proto_init() }
func file_original_url_proto_init() {
	if File_original_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_original_url_proto_rawDesc), len(file_original_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_original_url_proto_goTypes,
		DependencyIndexes: file_original_url_proto_depIdxs,
		MessageInfos:      file_original_url_proto_msgTypes,
	}.Build()
	File_original_url_proto = out.File
	file_original_url_proto_goTypes = nil
	file_original_url_proto_depIdxs = nil
}
