// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: short_url.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURL struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ShortUrl    *string                `protobuf:"bytes,1,opt,name=short_url,json=shortUrl"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_short_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ShortURL) GetShortUrl() string {
	if x != nil {
		if x.xxx_hidden_ShortUrl != nil {
			return *x.xxx_hidden_ShortUrl
		}
		return ""
	}
	return ""
}

func (x *ShortURL) SetShortUrl(v string) {
	x.xxx_hidden_ShortUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ShortURL) HasShortUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ShortURL) ClearShortUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ShortUrl = nil
}

type ShortURL_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortUrl *string
}

func (b0 ShortURL_builder) Build() *ShortURL {
	m0 := &ShortURL{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ShortUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ShortUrl = b.ShortUrl
	}
	return m0
}

var File_short_url_proto protoreflect.FileDescriptor

const file_short_url_proto_rawDesc = "" +
	"\n" +
	"\x0fshort_url.proto\x12\vproto.model\x1a!google/protobuf/go_features.proto\"'\n" +
	"\bShortURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrlBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_short_url_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_short_url_proto_goTypes = []any{
	(*ShortURL)(nil), // 0: proto.model.ShortURL
}
var file_short_url_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_short_url_proto_init() }
func file_short_url_proto_init() {
	if File_short_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_short_url_proto_rawDesc), len(file_short_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_short_url_proto_goTypes,
		DependencyIndexes: file_short_url_proto_depIdxs,
		MessageInfos:      file_short_url_proto_msgTypes,
	}.Build()
	File_short_url_proto = out.File
	file_short_url_proto_goTypes = nil
	file_short_url_proto_depIdxs = nil
}
