// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: stats_response.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Urls  *StatsURLs             `protobuf:"bytes,1,opt,name=urls"`
	xxx_hidden_Users *StatsUsers            `protobuf:"bytes,2,opt,name=users"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_stats_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsResponse) GetUrls() *StatsURLs {
	if x != nil {
		return x.xxx_hidden_Urls
	}
	return nil
}

func (x *StatsResponse) GetUsers() *StatsUsers {
	if x != nil {
		return x.xxx_hidden_Users
	}
	return nil
}

func (x *StatsResponse) SetUrls(v *StatsURLs) {
	x.xxx_hidden_Urls = v
}

func (x *StatsResponse) SetUsers(v *StatsUsers) {
	x.xxx_hidden_Users = v
}

func (x *StatsResponse) HasUrls() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Urls != nil
}

func (x *StatsResponse) HasUsers() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Users != nil
}

func (x *StatsResponse) ClearUrls() {
	x.xxx_hidden_Urls = nil
}

func (x *StatsResponse) ClearUsers() {
	x.xxx_hidden_Users = nil
}

type StatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Urls  *StatsURLs
	Users *StatsUsers
}

func (b0 StatsResponse_builder) Build() *StatsResponse {
	m0 := &StatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Urls = b.Urls
	x.xxx_hidden_Users = b.Users
	return m0
}

var File_stats_response_proto protoreflect.FileDescriptor

const file_stats_response_proto_rawDesc = "" +
	"\n" +
	"\x14stats_response.proto\x12\vproto.model\x1a\x10stats_urls.proto\x1a\x11stats_users.proto\x1a!google/protobuf/go_features.proto\"j\n" +
	"\rStatsResponse\x12*\n" +
	"\x04urls\x18\x01 \x01(\v2\x16.proto.model.StatsURLsR\x04urls\x12-\n" +
	"\x05users\x18\x02 \x01(\v2\x17.proto.model.StatsUsersR\x05usersBLZBgithub.com/RexArseny/url_shortener/internal/app/models/proto/model\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_stats_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stats_response_proto_goTypes = []any{
	(*StatsResponse)(nil), // 0: proto.model.StatsResponse
	(*StatsURLs)(nil),     // 1: proto.model.StatsURLs
	(*StatsUsers)(nil),    // 2: proto.model.StatsUsers
}
var file_stats_response_proto_depIdxs = []int32{
	1, // 0: proto.model.StatsResponse.urls:type_name -> proto.model.StatsURLs
	2, // 1: proto.model.StatsResponse.users:type_name -> proto.model.StatsUsers
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stats_response_proto_init() }
func file_stats_response_proto_init() {
	if File_stats_response_proto != nil {
		return
	}
	file_stats_urls_proto_init()
	file_stats_users_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_response_proto_rawDesc), len(file_stats_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stats_response_proto_goTypes,
		DependencyIndexes: file_stats_response_proto_depIdxs,
		MessageInfos:      file_stats_response_proto_msgTypes,
	}.Build()
	File_stats_response_proto = out.File
	file_stats_response_proto_goTypes = nil
	file_stats_response_proto_depIdxs = nil
}
